#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu May 23 14:42:48 UTC 2024
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_riscv_unit_behav -key {Behavioral:sim_1:Functional:tb_riscv_unit} -tclbatch tb_riscv_unit.tcl -view /home/pin_31_23/Desktop/periferal_units/tb_riscv_unit_behav.wcfg -log simulate.log"
xsim tb_riscv_unit_behav -key {Behavioral:sim_1:Functional:tb_riscv_unit} -tclbatch tb_riscv_unit.tcl -view /home/pin_31_23/Desktop/periferal_units/tb_riscv_unit_behav.wcfg -log simulate.log

