#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Apr 07 20:25:32 UTC 2024
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 5676052dfb5b4ba49e103ff4c991ae13 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_CYBERcobra_behav xil_defaultlib.tb_CYBERcobra xil_defaultlib.glbl -log elaborate.log"
xelab -wto 5676052dfb5b4ba49e103ff4c991ae13 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_CYBERcobra_behav xil_defaultlib.tb_CYBERcobra xil_defaultlib.glbl -log elaborate.log

